FROM ubuntu:20.04
LABEL description = "Dockerfile for building a docker image"
RUN apt update
RUN apt upgrade -y

RUN apt-get install -y python3
RUN apt-get install -y sqlite3
RUN apt install -y python3-pip



RUN pip3 install aiosqlite==0.17.0
RUN pip3 install anyio==3.6.1
RUN pip3 install asgiref==3.5.2
RUN pip3 install attrs==22.1.0
RUN pip3 install black==22.3.0
RUN pip3 install certifi==2022.6.15
RUN pip3 install charset-normalizer==2.1.0
RUN pip3 install cheroot==8.6.0
RUN pip3 install click==8.1.3
RUN pip3 install coverage==6.4.4
RUN pip3 install databases==0.6.0
RUN pip3 install fastapi==0.78.0
RUN pip3 install flake8==4.0.1
RUN pip3 install gcloud==0.17.0
RUN pip3 install googleapis-common-protos==1.56.4
RUN pip3 install greenlet==1.1.2
RUN pip3 install h11==0.13.0
RUN pip3 install httplib2==0.20.4
RUN pip3 install idna==3.3
RUN pip3 install iniconfig==1.1.1
RUN pip3 install isort==5.10.1
RUN pip3 install jaraco.functools==3.5.1
RUN pip3 install jws==0.1.3
RUN pip3 install mccabe==0.6.1
RUN pip3 install more-itertools==8.14.0
RUN pip3 install mypy==0.961
RUN pip3 install mypy-extensions==0.4.3
RUN pip3 install oauth2client==3.0.0
RUN pip3 install packaging==21.3
RUN pip3 install pathspec==0.9.0
RUN pip3 install platformdirs==2.5.2
RUN pip3 install pluggy==1.0.0
RUN pip3 install protobuf==4.21.5
RUN pip3 install py==1.11.0
RUN pip3 install pyasn1==0.4.8
RUN pip3 install pyasn1-modules==0.2.8
RUN pip3 install pycodestyle==2.8.0
RUN pip3 install pycryptodome==3.4.3
RUN pip3 install pydantic==1.9.2
RUN pip3 install pydocstyle==3.0.0
RUN pip3 install pyflakes==2.4.0
RUN pip3 install pyparsing==3.0.9
RUN pip3 install Pyrebase==3.0.27
RUN pip3 install pytest==7.1.1
RUN pip3 install pytest-cov==2.7.1
RUN pip3 install python-jwt==2.0.1
RUN pip3 install requests==2.11.1
RUN pip3 install requests-toolbelt==0.7.0
RUN pip3 install rsa==4.9
RUN pip3 install six==1.16.0
RUN pip3 install sniffio==1.2.0
RUN pip3 install snowballstemmer==2.2.0
RUN pip3 install SQLAlchemy==1.4.40
RUN pip3 install starlette==0.19.1
RUN pip3 install tomli==2.0.1
RUN pip3 install typing-extensions==4.3.0
RUN pip3 install urllib3==1.26.11
RUN pip3 install uvicorn==0.17.6
RUN pip3 install web.py==0.62